export const FETCH_ALL_START = 'FETCH_ALL_START';
export const FETCH_ALL_SUCCESS = 'FETCH_ALL_SUCCESS';
export const FETCH_ALL_FAILURE = 'FETCH_ALL_FAILURE';

export const FETCH_RESULT_LIST_START = 'FETCH_RESULT_LIST_START';
export const FETCH_RESULT_LIST_SUCCESS = 'FETCH_RESULT_LIST_SUCCESS';
export const FETCH_RESULT_LIST_FAILURE = 'FETCH_RESULT_LIST_FAILURE';

export const ADD_RESULT_LIST_START = 'ADD_RESULT_LIST_START';
export const ADD_RESULT_LIST_SUCCESS = 'ADD_RESULT_LIST_SUCCESS';
export const ADD_RESULT_LIST_FAILURE = 'ADD_RESULT_LIST_FAILURE';

export const EDIT_AMOUNT_SUCCESS = 'EDIT_AMOUNT_SUCCESS';
